// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: friend.proto

package contactV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FriendClient is the client API for Friend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendClient interface {
	Get(ctx context.Context, in *SearchFriendRequest, opts ...grpc.CallOption) (*FriendsResponse, error)
	Update(ctx context.Context, in *UpdateFriendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *UpdateFriendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetApply(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*FriendAppliesResponse, error)
	Apply(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ApplyAgree(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ApplyReject(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type friendClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendClient(cc grpc.ClientConnInterface) FriendClient {
	return &friendClient{cc}
}

func (c *friendClient) Get(ctx context.Context, in *SearchFriendRequest, opts ...grpc.CallOption) (*FriendsResponse, error) {
	out := new(FriendsResponse)
	err := c.cc.Invoke(ctx, "/contactPb.v1.friend/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) Update(ctx context.Context, in *UpdateFriendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/contactPb.v1.friend/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) Delete(ctx context.Context, in *UpdateFriendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/contactPb.v1.friend/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) GetApply(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*FriendAppliesResponse, error) {
	out := new(FriendAppliesResponse)
	err := c.cc.Invoke(ctx, "/contactPb.v1.friend/GetApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) Apply(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/contactPb.v1.friend/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) ApplyAgree(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/contactPb.v1.friend/ApplyAgree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) ApplyReject(ctx context.Context, in *UpdateFriendApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/contactPb.v1.friend/ApplyReject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServer is the server API for Friend service.
// All implementations must embed UnimplementedFriendServer
// for forward compatibility
type FriendServer interface {
	Get(context.Context, *SearchFriendRequest) (*FriendsResponse, error)
	Update(context.Context, *UpdateFriendRequest) (*emptypb.Empty, error)
	Delete(context.Context, *UpdateFriendRequest) (*emptypb.Empty, error)
	GetApply(context.Context, *UpdateFriendApplyRequest) (*FriendAppliesResponse, error)
	Apply(context.Context, *UpdateFriendApplyRequest) (*emptypb.Empty, error)
	ApplyAgree(context.Context, *UpdateFriendApplyRequest) (*emptypb.Empty, error)
	ApplyReject(context.Context, *UpdateFriendApplyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFriendServer()
}

// UnimplementedFriendServer must be embedded to have forward compatible implementations.
type UnimplementedFriendServer struct {
}

func (UnimplementedFriendServer) Get(context.Context, *SearchFriendRequest) (*FriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedFriendServer) Update(context.Context, *UpdateFriendRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedFriendServer) Delete(context.Context, *UpdateFriendRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedFriendServer) GetApply(context.Context, *UpdateFriendApplyRequest) (*FriendAppliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApply not implemented")
}
func (UnimplementedFriendServer) Apply(context.Context, *UpdateFriendApplyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedFriendServer) ApplyAgree(context.Context, *UpdateFriendApplyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyAgree not implemented")
}
func (UnimplementedFriendServer) ApplyReject(context.Context, *UpdateFriendApplyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyReject not implemented")
}
func (UnimplementedFriendServer) mustEmbedUnimplementedFriendServer() {}

// UnsafeFriendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServer will
// result in compilation errors.
type UnsafeFriendServer interface {
	mustEmbedUnimplementedFriendServer()
}

func RegisterFriendServer(s grpc.ServiceRegistrar, srv FriendServer) {
	s.RegisterService(&Friend_ServiceDesc, srv)
}

func _Friend_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactPb.v1.friend/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).Get(ctx, req.(*SearchFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactPb.v1.friend/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).Update(ctx, req.(*UpdateFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactPb.v1.friend/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).Delete(ctx, req.(*UpdateFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_GetApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).GetApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactPb.v1.friend/GetApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).GetApply(ctx, req.(*UpdateFriendApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactPb.v1.friend/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).Apply(ctx, req.(*UpdateFriendApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_ApplyAgree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).ApplyAgree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactPb.v1.friend/ApplyAgree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).ApplyAgree(ctx, req.(*UpdateFriendApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_ApplyReject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).ApplyReject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactPb.v1.friend/ApplyReject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).ApplyReject(ctx, req.(*UpdateFriendApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Friend_ServiceDesc is the grpc.ServiceDesc for Friend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contactPb.v1.friend",
	HandlerType: (*FriendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Friend_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Friend_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Friend_Delete_Handler,
		},
		{
			MethodName: "GetApply",
			Handler:    _Friend_GetApply_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Friend_Apply_Handler,
		},
		{
			MethodName: "ApplyAgree",
			Handler:    _Friend_ApplyAgree_Handler,
		},
		{
			MethodName: "ApplyReject",
			Handler:    _Friend_ApplyReject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "friend.proto",
}
